apiVersion: v1
kind: Service
metadata:
  name: {{ include "underleaf.fullname" . }}-collab
  labels:
    {{- include "underleaf.labels" . | nindent 4 }}
    app.kubernetes.io/component: collab
spec:
  type: {{ .Values.collab.service.type }}
  ports:
    - name: ws
      port: {{ .Values.collab.service.port }}
      targetPort: ws
      protocol: TCP
  selector:
    {{- include "underleaf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: collab
