apiVersion: v1
kind: Service
metadata:
  name: {{ include "underleaf.fullname" . }}-minio
  labels:
    {{- include "underleaf.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  ports:
    - name: minio-api
      port: 9000
      targetPort: minio-api
      protocol: TCP
    - name: minio-console
      port: 9001
      targetPort: minio-console
      protocol: TCP
  selector:
    {{- include "underleaf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
