apiVersion: v1
kind: Service
metadata:
  name: {{ include "underleaf.fullname" . }}-rabbitmq
  labels:
    {{- include "underleaf.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
    - name: management
      port: 15672
      targetPort: management
      protocol: TCP
  selector:
    {{- include "underleaf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
