apiVersion: v1
kind: Service
metadata:
  name: {{ include "underleaf.fullname" . }}-redis
  labels:
    {{- include "underleaf.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "underleaf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
