apiVersion: v1
kind: Secret
metadata:
  name: {{ include "underleaf.fullname" . }}-secret
  labels:
    {{- include "underleaf.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  minio-root-user: {{ .Values.minio.auth.rootUser | b64enc | quote }}
  minio-root-password: {{ .Values.minio.auth.rootPassword | b64enc | quote }}
  rabbitmq-username: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
  secret-key: {{ .Values.backend.env.secretKey | b64enc | quote }}
  anthropic-api-key: {{ .Values.backend.env.anthropicApiKey | b64enc | quote }}
  smtp-password: {{ .Values.backend.env.smtpPassword | b64enc | quote }}
